// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(HeroDbContext))]
    partial class HeroDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.HeroEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Height")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("HeroName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("Deleted");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("Deleted"), false);

                    b.ToTable("Heroes", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.HeroSuperPowerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("HeroId")
                        .HasColumnType("int");

                    b.Property<int>("SuperPowerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Deleted");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("Deleted"), false);

                    b.HasIndex("HeroId");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("HeroId"), false);

                    b.HasIndex("SuperPowerId");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("SuperPowerId"), false);

                    b.ToTable("HeroSuperPowers", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SuperPowerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("SuperPower")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Deleted");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("Deleted"), false);

                    b.ToTable("SuperPowers", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.HeroSuperPowerEntity", b =>
                {
                    b.HasOne("Domain.Entities.HeroEntity", "Hero")
                        .WithMany("HeroSuperPowers")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.SuperPowerEntity", "SuperPower")
                        .WithMany("HeroSuperPowers")
                        .HasForeignKey("SuperPowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");

                    b.Navigation("SuperPower");
                });

            modelBuilder.Entity("Domain.Entities.HeroEntity", b =>
                {
                    b.Navigation("HeroSuperPowers");
                });

            modelBuilder.Entity("Domain.Entities.SuperPowerEntity", b =>
                {
                    b.Navigation("HeroSuperPowers");
                });
#pragma warning restore 612, 618
        }
    }
}
